sonar.projectKey=nba-query-engine
sonar.projectName=NBA Query Engine
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=app,routes,config,resources/views,database/migrations
sonar.exclusions=vendor/**,storage/**,node_modules/**,bootstrap/cache/**,public/build/**,public/hot/**

sonar.tests=tests
sonar.test.exclusions=vendor/**,node_modules/**,storage/**

sonar.language=php

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=coverage.xml
